#!/bin/bash

# define tag value to use (defaults to +expire)

# find all tasks with $expire_tag 

# eliminate those with no due:date

# eliminate those with due:date > now

# modify all remaining tasks status:deleted

# exit

