#!/bin/bash

# define expite_tag value (defaults to +expire)

# confirmation option (0 = no confirmation, deafult is 1)

# find all tasks with $expire_tag 

# ignore those with no due:date

# ignore those with due:date > or = now

# modify all remaining tasks status:deleted

# echo actions taken summary notification

# exit

